#!/usr/bin/env python3
"""Generate a BibTeX of publications present on the website but NOT yet in ORCID.

Useful for topping up an ORCID record without creating duplicates: import the
output file into ORCID (Works -> Add -> Import BibTeX).

The set of works already in ORCID is identified by tolerant title matching
against ORCID_PRESENT below. Update that list whenever the ORCID record changes.

Run:  python3 scripts/generate_orcid_missing.py
Output: public/static/files/si_chen_orcid_missing.bib
"""
import json
import re
import os

from generate_bibtex import build_entry, make_key  # reuse shared logic

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "data", "publications.json")
OUT = os.path.join(ROOT, "public", "static", "files", "si_chen_orcid_missing.bib")

# Works already on the ORCID record (as of 2026-06-15). Matched tolerantly by a
# normalized prefix, so slight title variants (e.g. "Floor Plan" vs "Floor Plans")
# still match.
ORCID_PRESENT = [
    "A Privacy-Preserving Medical Data Sharing Scheme Based on Blockchain",
    "ARSpy: Breaking Location-Based Multi-Player Augmented Reality",
    "TT-SVD: An Efficient Sparse Decision",
    "PriWhisper+: An Enhanced Acoustic Short-Range",
    "DuoFS: A Hybrid Storage System",
    "You Can Hear But You Cannot Steal",
    "CrowdMap: Accurate Reconstruction of Indoor Floor",
    "Rise of the Indoor Crowd",
    "PriWhisper: Enabling Keyless Secure Acoustic Communication",
    "All Your Location Are Belong to Us",
    "Classification Model of Seed Cotton Grade",
    "Movement and Deformation of Virtual Object",
    "Research on the k-Coverage Local Wireless",
    "Simulation and Models on Control of Pests",
]


def norm(s):
    return re.sub(r"[^a-z0-9]", "", s.lower())


PRESENT_KEYS = [norm(t) for t in ORCID_PRESENT]


def in_orcid(title):
    nt = norm(title)
    for key in PRESENT_KEYS:
        probe = key[:22]
        if probe in nt or nt[:22] in key:
            return True
    return False


def main():
    with open(SRC, encoding="utf-8") as f:
        pubs = json.load(f)

    pubs = sorted(pubs, key=lambda p: (-int(p["year"]), p["type"]))
    missing = [p for p in pubs if not in_orcid(p["title"])]

    used = set()
    blocks = [
        "% Publications on https://sichen.dev NOT yet present in ORCID",
        "% Import into ORCID: Works -> Add -> Import BibTeX",
        "% Record: https://orcid.org/0000-0002-7117-4783",
        "% Generated by scripts/generate_orcid_missing.py",
        "",
    ]
    for entry in missing:
        key = make_key(entry, used)
        blocks.append(build_entry(entry, key))
        blocks.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(blocks))

    print("Wrote {} missing-from-ORCID entries to {}".format(len(missing), OUT))
    for p in missing:
        print("  {} | {}".format(p["year"], p["title"]))


if __name__ == "__main__":
    main()
