#!/usr/bin/env python3
"""Generate an ORCID-importable BibTeX file from src/data/publications.json.

Maps the site's `type` codes to BibTeX entry types:
    1 -> @inproceedings (Conference paper)
    2 -> @article       (Journal article)
    3 -> @misc          (Preprint)
    4 -> @incollection  (Book chapter)

Run:  python3 scripts/generate_bibtex.py
Output: public/static/files/si_chen_publications.bib
"""
import json
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "data", "publications.json")
OUT = os.path.join(ROOT, "public", "static", "files", "si_chen_publications.bib")

ENTRY_TYPE = {1: "inproceedings", 2: "article", 3: "misc", 4: "incollection"}

STOPWORDS = {"a", "an", "the", "on", "of", "for", "in", "and", "to", "with"}


def last_name(author_field):
    """Return the surname of the first author ('First Last' -> 'Last')."""
    first = author_field.split(",")[0].strip()
    parts = first.split()
    return parts[-1] if parts else "anon"


def first_title_word(title):
    for w in re.findall(r"[A-Za-z0-9]+", title):
        if w.lower() not in STOPWORDS:
            return w.lower()
    return "untitled"


def authors_to_bibtex(author_field):
    """Convert 'A B, C D' -> 'A B and C D'."""
    names = [a.strip() for a in author_field.split(",") if a.strip()]
    return " and ".join(names)


def esc(value):
    """Light escaping/cleanup for BibTeX field values."""
    if value is None:
        return ""
    return str(value).replace("&", r"\&").replace("%", r"\%").strip()


def make_key(entry, used):
    base = "{}{}{}".format(last_name(entry["author"]), entry["year"], first_title_word(entry["title"]))
    base = re.sub(r"[^A-Za-z0-9]", "", base)
    key = base
    i = 1
    while key in used:
        i += 1
        key = "{}{}".format(base, i)
    used.add(key)
    return key


def build_entry(entry, key):
    etype = ENTRY_TYPE.get(entry["type"], "misc")
    fields = []
    fields.append(("title", esc(entry["title"])))
    fields.append(("author", esc(authors_to_bibtex(entry["author"]))))

    venue = esc(entry.get("confname"))
    if etype == "article":
        if venue:
            fields.append(("journal", venue))
    elif etype == "inproceedings":
        if venue:
            fields.append(("booktitle", venue))
    elif etype == "incollection":
        if venue:
            fields.append(("booktitle", venue))
        fields.append(("publisher", "Springer"))
    else:  # misc / preprint
        if venue:
            fields.append(("howpublished", venue))

    fields.append(("year", str(entry["year"])))

    url = entry.get("urlpaper") or entry.get("urlpdf")
    if url and url.startswith("http"):
        fields.append(("url", esc(url)))

    note = esc(entry.get("text"))
    note = re.sub(r"[\U0001F000-\U0001FFFF☀-➿]", "", note).strip()
    if note:
        fields.append(("note", note))

    lines = ["@{}{{{},".format(etype, key)]
    for name, val in fields:
        if val:
            lines.append("  {:<13}= {{{}}},".format(name, val))
    # drop trailing comma on last field
    lines[-1] = lines[-1].rstrip(",")
    lines.append("}")
    return "\n".join(lines)


def main():
    with open(SRC, encoding="utf-8") as f:
        pubs = json.load(f)

    # newest first
    pubs = sorted(pubs, key=lambda p: (-int(p["year"]), p["type"]))

    used = set()
    blocks = [
        "% BibTeX export of Si Chen's publications",
        "% Source: https://sichen.dev  (src/data/publications.json)",
        "% Importable into ORCID: https://orcid.org/0000-0002-7117-4783",
        "% Generated by scripts/generate_bibtex.py",
        "",
    ]
    for entry in pubs:
        key = make_key(entry, used)
        blocks.append(build_entry(entry, key))
        blocks.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(blocks))

    print("Wrote {} entries to {}".format(len(pubs), OUT))


if __name__ == "__main__":
    main()
